# csclist.py – mapping of Samsung CSC codes to country/region names
#
# Author: Vladislav Tislenko (keklick1337), 2025
#
# Description:
#     This module defines CSC_DICT, a dictionary mapping 3‑letter Samsung CSC codes
#     to their corresponding country or region names.
#

CSC_DICT = {
    'AFG': 'AFGHANISTAN',
    'ALG': 'ALGERIA',
    'ALR': 'ALGERIA',
    'ANC': 'ARGENTINA',
    'ARO': 'ARGENTINA',
    'CTI': 'ARGENTINA',
    'UFN': 'ARGENTINA',
    'PSN': 'ARGENTINA',
    'ARU': 'ARUBA',
    'OPP': 'AUSTRALIA',
    'OPS': 'AUSTRALIA',
    'VAU': 'AUSTRALIA',
    'XSA': 'AUSTRALIA',
    'TEL': 'AUSTRALIA',
    'HUT': 'AUSTRALIA',
    'AOM': 'AUSTRIA',
    'DRE': 'AUSTRIA',
    'MAX': 'AUSTRIA',
    'MOB': 'AUSTRIA',
    'MOK': 'AUSTRIA',
    'ONE': 'AUSTRIA',
    'TRG': 'AUSTRIA',
    'ATO': 'AUSTRIA',
    'SEB': 'BALTICK',
    'BKD': 'BANGLADESH',
    'MTB': 'BELARUS',
    'VEL': 'BELARUS',
    'BAE': 'BELGIUM',
    'BSE': 'BELGIUM',
    'PRO': 'BELGIUM',
    'XEB': 'BELGIUM',
    'BHO': 'BOSNIA-HERZEGOVINA',
    'BHT': 'BOSNIA-HERZEGOVINA',
    'TEB': 'BOSNIA-HERZEGOVINA',
    'BTA': 'BRAZIL',
    'BTM': 'BRAZIL',
    'TMR': 'BRAZIL',
    'ZTA': 'BRAZIL',
    'ZVV': 'BRAZIL',
    'ZTO': 'BRAZIL',
    'ZTM': 'BRAZIL',
    'CMF': 'BULGARIA',
    'GBL': 'BULGARIA',
    'MTE': 'BULGARIA',
    'MTL': 'BULGARIA',
    'OMX': 'BULGARIA',
    'PLX': 'BULGARIA',
    'VVT': 'BULGARIA',
    'RCG': 'CAMBODIA',
    'RGS': 'CANADA',
    'BMC': 'CANADA',
    'TLS': 'CANADA',
    'CAU': 'CAUCASUS',
    'CHB': 'CHILE',
    'CHE': 'CHILE',
    'CHL': 'CHILE',
    'CHT': 'CHILE',
    'CUH': 'CHINA',
    'INT': 'CHINA',
    'TEC': 'CHINA',
    'TIY': 'CHINA',
    'CMC': 'CHINA',
    'CHN': 'CHINA',
    'M00': 'CHINA',
    'COB': 'COLOMBIA',
    'COL': 'COLOMBIA',
    'COM': 'COLOMBIA',
    'CGU': 'COLOMBIA',
    'ICE': 'COSTA RICA',
    'CRO': 'CROATIA',
    'TRA': 'CROATIA',
    'TWO': 'CROATIA',
    'VIP': 'CROATIA',
    'CYV': 'CYPRUS',
    'ETL': 'CZECH',
    'KBN': 'CZECH',
    'OSK': 'CZECH',
    'VDC': 'CZECH',
    'XCS': 'CZECH',
    'XEZ': 'CZECH',
    'TMZ': 'CZECH',
    'O2C': 'CZECH',
    'DTL': 'DENMARK',
    'CST': 'DOMINICA',
    'DCN': 'DOMINICA',
    'DOR': 'DOMINICA',
    'CDR': 'DOMINICAN REP.',
    'TDR': 'DOMINICAN REP.',
    'BBE': 'ECUADOR',
    'EGY': 'EGYPT',
    'DGC': 'EL SALVADOR',
    'TBS': 'EL SALVADOR',
    'EUX': 'EUROPE',
    'EUY': 'EUROPE',
    'ELS': 'FINLAND',
    'SAU': 'FINLAND',
    'OFR': 'FRANCE',
    'AUC': 'FRANCE',
    'BOG': 'FRANCE',
    'COR': 'FRANCE',
    'DIX': 'FRANCE',
    'FTM': 'FRANCE',
    'NRJ': 'FRANCE',
    'ORC': 'FRANCE',
    'ORF': 'FRANCE',
    'SFR': 'FRANCE',
    'UNI': 'FRANCE',
    'VGF': 'FRANCE',
    'XEF': 'FRANCE',
    'DBT': 'GERMANY',
    'DTM': 'GERMANY',
    'DUT': 'GERMANY',
    'EPL': 'GERMANY',
    'MAN': 'GERMANY',
    'MBC': 'GERMANY',
    'VD2': 'GERMANY',
    'VIA': 'GERMANY',
    'XEG': 'GERMANY',
    'SPN': 'GHANA',
    'AOC': 'GREECE',
    'COS': 'GREECE',
    'EUR': 'GREECE',
    'GER': 'GREECE',
    'TGR': 'GREECE',
    'VGR': 'GREECE',
    'CYO': 'GREECE',
    'PCS': 'GUATEMALA',
    'TGY': 'HONG KONG',
    'PAN': 'HUNGARY',
    'VDH': 'HUNGARY',
    'WST': 'HUNGARY',
    'TMO': 'HUNGARY',
    'XEH': 'HUNGARY',
    'TMH': 'HUNGARY',
    'HFC': 'INDIA',
    'HYA': 'INDIA',
    'INA': 'INDIA',
    'IND': 'INDIA',
    'INU': 'INDIA',
    'IMS': 'INDIA',
    'REL': 'INDIA',
    'TAT': 'INDIA',
    'INS': 'INDIA',
    'AXI': 'INDONESIA',
    'SAR': 'INDONESIA',
    'XSE': 'INDONESIA',
    'THR': 'IRAN',
    '3IE': 'IRELAND',
    'VDI': 'IRELAND',
    'MET': 'IRELAND',
    'CEL': 'ISRAEL',
    'PCL': 'ISRAEL',
    'PTR': 'ISRAEL',
    'ILO': 'ISRAEL',
    'GOM': 'ITALY',
    'HUI': 'ITALY',
    'ITV': 'ITALY',
    'OMN': 'ITALY',
    'TIM': 'ITALY',
    'VOM': 'ITALY',
    'WIN': 'ITALY',
    'XET': 'ITALY',
    'FWB': 'ITALY',
    'IRS': 'IVORY COAST',
    'SIE': 'IVORY COAST',
    'JBS': 'JAMAICA',
    'JCN': 'JAMAICA',
    'JCW': 'JAMAICA',
    'DCM': 'JAPAN',
    'SBM': 'JAPAN',
    'VFK': 'JAPAN',
    'LEV': 'JORDAN',
    'EST': 'KAZAKHSTAN',
    'KCL': 'KAZAKHSTAN',
    'KMB': 'KAZAKHSTAN',
    'KZK': 'KAZAKHSTAN',
    'SKZ': 'KAZAKHSTAN',
    'KEL': 'KENYA',
    'KEN': 'KENYA',
    'DKR': 'KENYA',
    'SKT': 'KOREA',
    'FYC': 'LIBYA',
    'MMC': 'LIBYAN ARAB REP',
    'TLT': 'LITHUANIA',
    'ILP': 'LEBANON',
    'LUX': 'LUXEMBURG',
    'VTN': 'MACAO',
    'TMC': 'MACEDONIA',
    'MBM': 'MACEDONIA',
    'CCM': 'MALAYSIA',
    'MXS': 'MALAYSIA',
    'FMG': 'MALAYSIA',
    'FME': 'MALAYSIA',
    'XME': 'MALAYSIA',
    'SEM': 'MEXICO',
    'TCE': 'MEXICO',
    'TMM': 'MEXICO',
    'UNE': 'MEXICO',
    'MEA': 'MIDDLE EAST AND AFRICA',
    'MPC': 'MONGOLIA',
    'WAN': 'MOROCCO',
    'FWD': 'MOROCCO',
    'MAT': 'MOROCCO',
    'MED': 'MOROCCO',
    'SNI': 'MOROCCO',
    'MWD': 'MOROCCO',
    'NPB': 'NEPAL',
    'BEN': 'NETHERLANDS',
    'MMO': 'NETHERLANDS',
    'ONL': 'NETHERLANDS',
    'QIC': 'NETHERLANDS',
    'TFT': 'NETHERLANDS',
    'TNL': 'NETHERLANDS',
    'VDF': 'NETHERLANDS',
    'VDP': 'NETHERLANDS',
    'XEN': 'NETHERLANDS',
    'KPN': 'NETHERLANDS',
    'VNZ': 'NEW ZEALAND',
    'XNZ': 'NEW ZEALAND',
    'ECT': 'NIGERIA',
    'GCR': 'NIGERIA',
    'MML': 'NIGERIA',
    'TEN': 'NORWAY',
    'WDC': 'PAKISTAN',
    'PAK': 'PAKISTAN',
    'PKD': 'PAKISTAN',
    'BPC': 'PANAMA',
    'PCW': 'PANAMA',
    'PBS': 'PANAMA',
    'PEB': 'PERU',
    'PET': 'PERU',
    'SAM': 'PERU',
    'FAM': 'PHILIPPINES',
    'XTC': 'PHILIPPINES',
    'GLB': 'PHILIPPINES',
    'XTE': 'PHILIPPINES',
    'SMA': 'PHILIPPINES',
    'ERA': 'POLAND',
    'IDE': 'POLAND',
    'PLS': 'POLAND',
    'PRT': 'POLAND',
    'XEO': 'POLAND',
    'OPT': 'PORTUGAL',
    'TMN': 'PORTUGAL',
    'TPH': 'PORTUGAL',
    'XEP': 'PORTUGAL',
    'TCL': 'PORTUGAL',
    'MEO': 'PORTUGAL',
    'CEN': 'PUERTO RICO',
    'PCI': 'PUERTO RICO',
    'TPR': 'PUERTO RICO',
    'CNX': 'ROMANIA',
    'HAT': 'ROMANIA',
    'ORO': 'ROMANIA',
    'COA': 'ROMANIA',
    'AZC': 'RUSSIA',
    'BLN': 'RUSSIA',
    'EMT': 'RUSSIA',
    'ERS': 'RUSSIA',
    'GEO': 'RUSSIA',
    'MTV': 'RUSSIA',
    'SER': 'RUSSIA',
    'SNT': 'RUSSIA',
    'WWA': 'SAMPLE',
    'WWC': 'SAMPLE',
    'WWD': 'SAMPLE',
    'JED': 'SAUDI ARABIA',
    'ACR': 'SAUDI ARABIA',
    'KSA': 'SAUDI ARABIA',
    'MSR': 'SERBIA MONTENEGRO',
    'PMN': 'SERBIA MONTENEGRO',
    'SMO': 'SERBIA MONTENEGRO',
    'TSR': 'SERBIA MONTENEGRO',
    'TOP': 'SERBIA MONTENEGRO',
    'BGD': 'SINGAPORE',
    'XSO': 'SINGAPORE',
    'XSP': 'SINGAPORE',
    'MM1': 'SINGAPORE',
    'SIN': 'SINGAPORE',
    'STH': 'SINGAPORE (STARHUB)',
    'GTL': 'SLOVAKIA',
    'IRD': 'SLOVAKIA',
    'TMS': 'SLOVAKIA',
    'ORS': 'SLOVAKIA',
    'MOT': 'SLOVENIA',
    'SIM': 'SLOVENIA',
    'XFA': 'SOUTH AFRICA',
    'XFC': 'SOUTH AFRICA',
    'XFM': 'SOUTH AFRICA',
    'XFE': 'SOUTH AFRICA',
    'XFV': 'SOUTH ARFICA',
    'SWA': 'SOUTHWEST ASIA',
    'AMN': 'SPAIN',
    'EUS': 'SPAIN',
    'FOP': 'SPAIN',
    'XEC': 'SPAIN',
    'ATL': 'SPAIN',
    'SLK': 'SRI LANKA',
    'BAU': 'SWEDEN',
    'BCN': 'SWEDEN',
    'BME': 'SWEDEN',
    'BSG': 'SWEDEN',
    'BTH': 'SWEDEN',
    'COV': 'SWEDEN',
    'HTS': 'SWEDEN',
    'SEN': 'SWEDEN',
    'TET': 'SWEDEN',
    'TLA': 'SWEDEN',
    'XEE': 'SWEDEN',
    'VDS': 'SWEDEN',
    'TNO': 'SWEDEN',
    'AUT': 'SWITZERLAND',
    'ORG': 'SWITZERLAND',
    'MOZ': 'SWITZERLAND',
    'SUN': 'SWITZERLAND',
    'SWC': 'SWITZERLAND',
    'TWM': 'TAIWAN',
    'BRI': 'TAIWAN',
    'TCC': 'TAIWAN',
    'TCI': 'TAIWAN',
    'CWT': 'TAIWAN',
    'TEM': 'TEMPORARY',
    'CAT': 'THAILAND',
    'THE': 'THAILAND',
    'THL': 'THAILAND',
    'THO': 'THAILAND',
    'THS': 'THAILAND',
    'ABS': 'TUNISIA',
    'RNG': 'TUNISIA',
    'TUN': 'TUNISIA',
    'BAS': 'TURKEY',
    'KVK': 'TURKEY',
    'TUR': 'TURKEY',
    'TLP': 'TURKEY',
    'TRC': 'TURKEY',
    'SOL': 'Tanzania',
    'KVR': 'UKRAINE',
    'SEK': 'UKRAINE',
    'UMC': 'UKRAINE',
    'MID': 'UNITED ARAB EMIRATES',
    'ARB': 'UNITED ARAB EMIRATES',
    'XSG': 'UNITED ARAB EMIRATES',
    'AFR': 'UNITED ARAB EMIRATES',
    'ITO': 'UNITED ARAB EMIRATES',
    'LYS': 'UNITED ARAB EMIRATES',
    'BTC': 'UNITED KINGDOM',
    'O2I': 'UNITED KINGDOM',
    'O2U': 'UNITED KINGDOM',
    'ORA': 'UNITED KINGDOM',
    'TMU': 'UNITED KINGDOM',
    'TSC': 'UNITED KINGDOM',
    'VOD': 'UNITED KINGDOM',
    'XEU': 'UNITED KINGDOM',
    'VIR': 'UNITED KINGDOM',
    'H3G': 'UNITED KINGDOM',
    'CPW': 'UNITED KINGDOM',
    'EVR': 'UNITED KINGDOM',
    'AWS': 'USA',
    'DOB': 'USA',
    'TMB': 'USA',
    'CLW': 'USA',
    'UZB': 'UZBEKISTAN',
    'VMT': 'VENEZUELA',
    'XXV': 'VIETNAM',
    'PHU': 'VIETNAM',
    'XEV': 'VIETNAM',
    'DNA': 'VIETNAM',
    'FPT': 'VIETNAM',
    'SPT': 'VIETNAM',
    'TLC': 'VIETNAM',
    'VTC': 'VIETNAM',
    'VTL': 'VIETNAM',
}
