# csclist.py – mapping of Samsung CSC codes to country/region names
#
# Author: Vladislav Tislenko (keklick1337), 2025
#
# Description:
#     This module defines CSC_DICT, a dictionary mapping 3‑letter Samsung CSC codes
#     to their corresponding country or region names.
#

CSC_DICT = {
    # United States of America
    #'OYM': 'XAA',
    #'OYN': 'ATT, VZW, TMB, USC, XAA',

    # France, Germany, Italy, Poland, United Kingdom
    #'OXA': 'BTU, CPW, DBT, ITV, KOR, XEF, XEO',

    # Kazakhstan, Russia, United Arab Emirates
    #'OXE': 'CAC, RTL, SEK, SER, SKZ',
    #'QXE': 'OXE LAFLEUR',

    # Malaysia, Philippines, Thailand, Vietnam
    #'OLB': 'GLB, MM1, SIN, SMA, STH, THL, XEV, XME, XSE, XSP, XTC, XTE, XXV',

    # Middle East Countries
    #'OJP': 'BTC, EGY, JED, KOR, KSA, MAT, MED, MID, MMV, MWD, PAK, THR, WAN, XSG, XSS',
    #'OJV': 'ABS, ACR, AFG, AFR, ARB, BTC, ECT, EGY, FWD, JED, KEN, KSA, LYS, MAT, MED, MID, MMC, MRT, MWD, PAK, THR, TMC, TUN, TUR, WAN, WTL, XFA, XFC, XFE, XFM, XFV, XSG',

    # Vodafone
    #'VFG': 'ATL, CNX, CYV, MOB, MTL, OMN, PRO, SFR, SIM, SWC, TCL, TOP, V D2, VDC, VDF, VDH, VDI, VDP, VDR, VGR, VIP, VOD, VOP',
    #'YFG': 'VFG BLACK EDITION',
    #'VFR': 'ATL, OMN, VD2, VDF, VOD',
    
    #'OXF': 'ALB, BGL, CMF, ORL, SEB, TMT, TOP, TRA, XEH',
    #'OXX': 'BGL, CYO, ERO, EUR, MSR, ORS, PHE, SEE, SIO, TPH, TSR, TWO, VVT, XEF, XEO, XEZ, XSK',
    #'YXX': 'OXX BLACK EDITION',
    #'QXX': 'OXX LAFLEUR',
    #'OYA': 'BMC, BWA, FMC, KDO, MTA, PCM, RWC, SOL, SPC, TLS, VMC',
    #'OJK': 'ILO, MIR, PCL, PTR',
    #'ODD': 'INU, INS, ETR, TML, SLK, NPL',
    #'OLC': 'MM1, SIN, STH, XSP',
    #'OZS': 'TGY, BRI',
    #'YXY': 'ATO, AUO, AUT, BOG, BTU, EUR, GBL, ITV, MOT BLACK EDITION',
    #'OWO': 'PEO, ZTO, SEM, CHO, COO, PEB, TPA, VNO, ARO, BBR, DGC, PCS, TPR',
    #'OXM': 'ACR, AFG, AFR, AUT, BKD, BOG, BTB, BTE, BTU, CAU, CPW, DBT, DKR, ECT, EGY, EUX, EVR, FWD, GLB, ILO, ILP, INS, KSA, LYS, MEO, MET, MID, MM1, MOB, MOT, MSR, MWD, NPL, O2C, OPS, PKD, PLS, PRT, SEK, SER, SFR, SIM, SIN, SKZ, SLK, STH, SWC, TEL, THL, TIM, TOP, TSI, TUN, TUR, VAU, VIP, WWA, WWC, WWD, XEF, XFA, XFE, XFV, XME, XNZ, XSA, XSG, XSP',
    #'UWA': 'CDR, PCT',
    #'UVC': 'CTI, CTP, CTU',
    #'OXI': 'ITV, OMN',
    #'UVY': 'IUS, UNE',
    
    'AFG': 'AFGHANISTAN',
    'ALB': 'ALBANIA',
    'AVF': 'ALBANIA',
    'ALG': 'ALGERIA',
    'ALR': 'ALGERIA',
    'BLA': 'ALGERIA',
    'NED': 'ALGERIA',
    'SAC': 'ALGERIA',
    'TMA': 'ALGERIA',
    'WTL': 'ALGERIA',
    'XFU': 'ANGOLA',
    'ANC': 'ARGENTINA',
    'ARO': 'ARGENTINA',
    'CTI': 'ARGENTINA',
    'UFN': 'ARGENTINA',
    'PSN': 'ARGENTINA',
    'CTU': 'ARGENTINA URUGUAY',
    'ARU': 'ARUBA',
    'BST': 'AUSTRALIA',
    'OPP': 'AUSTRALIA',
    'OPS': 'AUSTRALIA',
    'VAU': 'AUSTRALIA',
    'XSA': 'AUSTRALIA',
    'TEL': 'AUSTRALIA',
    'HUT': 'AUSTRALIA',
    'VAP': 'AUSTRALIA',
    'AOM': 'AUSTRIA',
    'DRE': 'AUSTRIA',
    'MAX': 'AUSTRIA',
    'MOB': 'AUSTRIA',
    'MOK': 'AUSTRIA',
    'ONE': 'AUSTRIA',
    'TRG': 'AUSTRIA',
    'ATO': 'AUSTRIA',
    'QTO': 'ATO LAFLEUR',
    'TTR': 'AUSTRIA',
    'SEB': 'BALTICK',
    'BKD': 'BANGLADESH',
    'BNG': 'BANGLADESH',
    'ETR': 'BANGLADESH',
    'TML': 'BANGLADESH',
    'MTB': 'BELARUS',
    'VEL': 'BELARUS',
    'BAE': 'BELGIUM',
    'BSE': 'BELGIUM',
    'MST': 'BELGIUM',
    'PHB': 'BELGIUM',
    'PRO': 'BELGIUM',
    'TLB': 'BELGIUM',
    'XEB': 'BELGIUM',
    'BVE': 'BOLIVIA',
    'BVO': 'BOLIVIA',
    'ERO': 'BOSNIA-HERZEGOVINA',
    'BHO': 'BOSNIA-HERZEGOVINA',
    'BHT': 'BOSNIA-HERZEGOVINA',
    'TEB': 'BOSNIA-HERZEGOVINA',
    'ZTR': 'BRASIL',
    'BTA': 'BRAZIL',
    'BTM': 'BRAZIL',
    'TMR': 'BRAZIL',
    'ZTA': 'BRAZIL',
    'ZVV': 'BRAZIL',
    'ZTO': 'BRAZIL',
    'BGL': 'BULGARIA',
    'ZTM': 'BRAZIL',
    'CMF': 'BULGARIA',
    'GBL': 'BULGARIA',
    'MTE': 'BULGARIA',
    'MTL': 'BULGARIA',
    'OMX': 'BULGARIA',
    'PLX': 'BULGARIA',
    'VVT': 'BULGARIA',
    'RCG': 'CAMBODIA',
    'RGS': 'CANADA',
    'BMC': 'CANADA',
    'BWA': 'CANADA',
    'CLN': 'CANADA',
    'ESK': 'CANADA',
    'FMC': 'CANADA',
    'GLW': 'CANADA',
    'KDO': 'CANADA',
    'MCT': 'CANADA',
    'MTA': 'CANADA',
    'MTR': 'CANADA',
    'PCM': 'CANADA',
    'RWC': 'CANADA',
    'SPC': 'CANADA',
    'TLS': 'CANADA',
    'VMC': 'CANADA',
    'VTR': 'CANADA',
    'XAC': 'CANADA',
    'GWL': 'CANADA',
    'CAU': 'CAUCASUS',
    'CHB': 'CHILE',
    'CHE': 'CHILE',
    'CHF': 'CHILE',
    'CHG': 'CHILE',
    'CHL': 'CHILE',
    'CHO': 'CHILE',
    'CHT': 'CHILE',
    'CHV': 'CHILE',
    'CHX': 'CHILE',
    'CHC': 'CHINA',
    'CHM': 'CHINA',
    'CHU': 'CHINA',
    'CTC': 'CHINA',
    'CUH': 'CHINA',
    'INT': 'CHINA',
    'TEC': 'CHINA',
    'TIY': 'CHINA',
    'UWE': 'CLARO',
    'CMC': 'CHINA',
    'CHN': 'CHINA',
    'M00': 'CHINA',
    'COB': 'COLOMBIA',
    'COL': 'COLOMBIA',
    'COM': 'COLOMBIA',
    'COO': 'COLOMBIA',
    'CGU': 'COLOMBIA',
    'COD': 'COLOMBIA AVANCEL',
    'COE': 'COLOMBIA ETB',
    'CRC': 'COSTA RICA',
    'ICE': 'COSTA RICA',
    'CRO': 'CROATIA',
    'DHR': 'CROATIA',
    'TRA': 'CROATIA',
    'TWO': 'CROATIA',
    'VIP': 'CROATIA',
    'CYV': 'CYPRUS',
    'ETL': 'CZECH',
    'KBN': 'CZECH',
    'OSK': 'CZECH',
    'VDC': 'CZECH',
    'XCS': 'CZECH',
    'XEZ': 'CZECH',
    'TMZ': 'CZECH',
    'O2C': 'CZECH',
    'DTL': 'DENMARK',
    'HTD': 'DENMARK',
    'ODK': 'DENMARK',
    'TDC': 'DENMARK',
    'CST': 'DOMINICA',
    'DCN': 'DOMINICA',
    'DOR': 'DOMINICA',
    'CDR': 'DOMINICAN REP.',
    'TDR': 'DOMINICAN REP.',
    'ALE': 'ECUADOR',
    'BBE': 'ECUADOR',
    'EBE': 'ECUADOR',
    'ECO': 'ECUADOR',
    'EON': 'ECUADOR',
    'EGY': 'EGYPT',
    'DGC': 'EL SALVADOR',
    'ETE': 'EL SALVADOR',
    'PER': 'EL SALVADOR',
    'SAL': 'EL SALVADOR',
    'TBS': 'EL SALVADOR',
    'EUX': 'EUROPE',
    'EUY': 'EUROPE',
    'PAP': 'EUROPE',
    'VFJ': 'FIJI',
    'DNF': 'FINLAND',
    'ELS': 'FINLAND',
    'SAU': 'FINLAND',
    'OFR': 'FRANCE',
    'AUC': 'FRANCE',
    'BOG': 'FRANCE',
    'COR': 'FRANCE',
    'DIX': 'FRANCE',
    'FNC': 'FRANCE',
    'FRE': 'FRANCE',
    'FTM': 'FRANCE',
    'LPM': 'FRANCE',
    'NRJ': 'FRANCE',
    'ORC': 'FRANCE',
    'ORF': 'FRANCE',
    'SFR': 'FRANCE',
    'UNI': 'FRANCE',
    'VGF': 'FRANCE',
    'XEF': 'FRANCE',
    'DBT': 'GERMANY',
    'DDE': 'GERMANY',
    'DTM': 'GERMANY',
    'DTR': 'GERMANY',
    'DUT': 'GERMANY',
    'EPL': 'GERMANY',
    'MAN': 'GERMANY',
    'MBC': 'GERMANY',
    'VD2': 'GERMANY',
    'VDR': 'GERMANY',
    'VIA': 'GERMANY',
    'VIT': 'GERMANY',
    'XEG': 'GERMANY',
    'ACA': 'GHANA',
    'GHA': 'GHANA',
    'SPN': 'GHANA',
    'AOC': 'GREECE',
    'COS': 'GREECE',
    'EUR': 'GREECE',
    'GER': 'GREECE',
    'TGR': 'GREECE',
    'VGR': 'GREECE',
    'CYO': 'GREECE',
    'PCS': 'GUATEMALA',
    'PGU': 'GUATEMALA',
    'TGU': 'GUATEMALA',
    'CTE': 'HONDURAS',
    'HME': 'HONDURAS',
    'TGY': 'HONG KONG',
    'PAN': 'HUNGARY',
    'VDH': 'HUNGARY',
    'WST': 'HUNGARY',
    'TMO': 'HUNGARY',
    'XEH': 'HUNGARY',
    'TMH': 'HUNGARY',
    'HFC': 'INDIA',
    'HYA': 'INDIA',
    'INA': 'INDIA',
    'IND': 'INDIA',
    'INU': 'INDIA',
    'IMS': 'INDIA',
    'REL': 'INDIA',
    'TAT': 'INDIA',
    'INS': 'INDIA',
    'AXI': 'INDONESIA',
    'SAR': 'INDONESIA',
    'XID': 'INDONESIA',
    'XSE': 'INDONESIA',
    'THR': 'IRAN',
    '3IE': 'IRELAND',
    'EIR': 'IRELAND',
    'TSI': 'IRELAND',
    'VDI': 'IRELAND',
    'MET': 'IRELAND',
    'CEL': 'ISRAEL',
    'MIR': 'ISRAEL',
    'PCL': 'ISRAEL',
    'PTR': 'ISRAEL',
    'ILO': 'ISRAEL',
    'CIT': 'ITALY',
    'GOM': 'ITALY',
    'HUI': 'ITALY',
    'ITA': 'ITALY',
    'ITV': 'ITALY',
    'OMN': 'ITALY',
    'TIM': 'ITALY',
    'VOM': 'ITALY',
    'WIN': 'ITALY',
    'XET': 'ITALY',
    'FWB': 'ITALY',
    'IRS': 'IVORY COAST',
    'SIE': 'IVORY COAST',
    'CWW': 'JAMAICA',
    'JBS': 'JAMAICA',
    'JCN': 'JAMAICA',
    'JCW': 'JAMAICA',
    'JDI': 'JAMAICA',
    'DCM': 'JAPAN',
    'KDI': 'JAPAN',
    'SBM': 'JAPAN',
    'VFK': 'JAPAN',
    'XJP': 'JAPAN',
    'LEV': 'JORDAN',
    'ALT': 'KAZAKHSTAN',
    'EST': 'KAZAKHSTAN',
    'KCL': 'KAZAKHSTAN',
    'KMB': 'KAZAKHSTAN',
    'KZK': 'KAZAKHSTAN',
    'SKZ': 'KAZAKHSTAN',
    'DRC': 'KENYA',
    'ETT': 'KENYA',
    'KEL': 'KENYA',
    'KEN': 'KENYA',
    'DKR': 'KENYA',
    'SAF': 'KENYA',
    'ANY': 'KOREA',
    'KOO': 'KOREA',
    'KOR': 'KOREA',
    'KTC': 'KOREA',
    'KTO': 'KOREA',
    'KTT': 'KOREA',
    'LGT': 'KOREA',
    'LUC': 'KOREA',
    'LUO': 'KOREA',
    'SKC': 'KOREA',
    'SKO': 'KOREA',
    'SKT': 'KOREA',
    'XSZ': 'KUWAIT',
    'FYC': 'LIBYA',
    'MMC': 'LIBYAN ARAB REP',
    'TLT': 'LITHUANIA',
    'ILP': 'LEBANON',
    'DAM': 'LEBANON',
    'LEB': 'LEBANON',
    'LUX': 'LUXEMBURG',
    'VTN': 'MACAO',
    'TMC': 'MACEDONIA',
    'MBM': 'MACEDONIA',
    'MKO': 'MACEDONIA',
    'VIM': 'MACEDONIA',
    'CCM': 'MALAYSIA',
    'MXS': 'MALAYSIA',
    'FMG': 'MALAYSIA',
    'DGI': 'MALAYSIA',
    'FME': 'MALAYSIA',
    'MIS': 'MALAYSIA',
    'UMB': 'MALAYSIA',
    'XME': 'MALAYSIA',
    'MRT': 'MAURITANIA',
    'MRU': 'MAURITIUS',
    'IUS': 'MEXICO',
    'MNX': 'MEXICO',
    'SEM': 'MEXICO',
    'TCE': 'MEXICO',
    'TMM': 'MEXICO',
    'UNE': 'MEXICO',
    'MEA': 'MIDDLE EAST AND AFRICA',
    'MPC': 'MONGOLIA',
    'TMT': 'MONTENEGRO',
    'TEM': 'MONTENEGRO',
    'WAN': 'MOROCCO',
    'FWD': 'MOROCCO',
    'MAT': 'MOROCCO',
    'MED': 'MOROCCO',
    'SNI': 'MOROCCO',
    'MWD': 'MOROCCO',
    'XFN': 'NAMIBIA',
    'NPB': 'NEPAL',
    'NPL': 'NEPAL',
    'BEN': 'NETHERLANDS',
    'DBE': 'NETHERLANDS',
    'DNL': 'NETHERLANDS',
    'KPP': 'NETHERLANDS',
    'MMO': 'NETHERLANDS',
    'ONL': 'NETHERLANDS',
    'PHN': 'NETHERLANDS',
    'QIC': 'NETHERLANDS',
    'TFT': 'NETHERLANDS',
    'TNL': 'NETHERLANDS',
    'TPD': 'NETHERLANDS',
    'VDF': 'NETHERLANDS',
    'VDP': 'NETHERLANDS',
    'XEN': 'NETHERLANDS',
    'KPN': 'NETHERLANDS',
    'NZC': 'NEW ZEALAND',
    'TNX': 'NEW ZEALAND',
    'TNZ': 'NEW ZEALAND',
    'VNX': 'NEW ZEALAND',
    'VNZ': 'NEW ZEALAND',
    'XNZ': 'NEW ZEALAND',
    'NBS': 'NICARAGUA',
    'NEN': 'NICARAGUA',
    'AND': 'NIGERIA',
    'ECT': 'NIGERIA',
    'GCR': 'NIGERIA',
    'IEL': 'NIGERIA',
    'MML': 'NIGERIA',
    'NEE': 'NORDIC',
    'TEN': 'NORWAY',
    'CRM': 'OPEN SOUTH AMERICA',
    'WDC': 'PAKISTAN',
    'PAK': 'PAKISTAN',
    'PKD': 'PAKISTAN',
    'BPC': 'PANAMA',
    'PCW': 'PANAMA',
    'CPA': 'PANAMA',
    'PBS': 'PANAMA',
    'TPA': 'PANAMA',
    'PNG': 'PAPUA NEW GUINEA',
    'CTP': 'PARAGUAY',
    'TGP': 'PARAGUAY',
    'UPO': 'PARAGUAY',
    'VOX': 'PARAGUAY',
    'PEB': 'PERU',
    'PEO': 'PERU',
    'PET': 'PERU',
    'PNT': 'PERU',
    'PVT': 'PERU',
    'SAM': 'PERU',
    'FAM': 'PHILIPPINES',
    'XTC': 'PHILIPPINES',
    'GLB': 'PHILIPPINES',
    'XTE': 'PHILIPPINES',
    'SMA': 'PHILIPPINES',
    'DPL': 'POLAND',
    'ERA': 'POLAND',
    'IDE': 'POLAND',
    'PLS': 'POLAND',
    'POL': 'POLAND',
    'PRT': 'POLAND',
    'TPL': 'POLAND',
    'XEO': 'POLAND',
    'OPT': 'PORTUGAL',
    'TMN': 'PORTUGAL',
    'TPH': 'PORTUGAL',
    'XEP': 'PORTUGAL',
    'TCL': 'PORTUGAL',
    'MEO': 'PORTUGAL',
    'CEN': 'PUERTO RICO',
    'PCI': 'PUERTO RICO',
    'PCT': 'PUERTO RICO',
    'TPR': 'PUERTO RICO',
    'CNX': 'ROMANIA',
    'HAT': 'ROMANIA',
    'ORO': 'ROMANIA',
    'COA': 'ROMANIA',
    'ORL': 'ROMANIA',
    'ROM': 'ROMANIA',
    'AZC': 'RUSSIA',
    'BLN': 'RUSSIA',
    'BLR': 'RUSSIA',
    'EMT': 'RUSSIA',
    'ERS': 'RUSSIA',
    'GEO': 'RUSSIA',
    'MGF': 'RUSSIA',
    'MTV': 'RUSSIA',
    'SCA': 'RUSSIA',
    'SER': 'RUSSIA',
    'SNT': 'RUSSIA',
    'SVZ': 'RUSSIA',
    'WWA': 'SAMPLE',
    'WWC': 'SAMPLE',
    'WWD': 'SAMPLE',
    'JED': 'SAUDI ARABIA',
    'ACR': 'SAUDI ARABIA',
    'HAJ': 'SAUDI ARABIA',
    'KSA': 'SAUDI ARABIA',
    'KSZ': 'SAUDI ARABIA',
    'SEE': 'SEAD SERBIA',
    'MSR': 'SERBIA MONTENEGRO',
    'PMN': 'SERBIA MONTENEGRO',
    'SMO': 'SERBIA MONTENEGRO',
    'TSR': 'SERBIA MONTENEGRO',
    'TOP': 'SERBIA MONTENEGRO',
    'BGD': 'SINGAPORE',
    'XSO': 'SINGAPORE',
    'XSP': 'SINGAPORE',
    'MM1': 'SINGAPORE',
    'SIN': 'SINGAPORE',
    'STH': 'SINGAPORE (STARHUB)',
    'GTL': 'SLOVAKIA',
    'IRD': 'SLOVAKIA',
    'TMS': 'SLOVAKIA',
    'ORS': 'SLOVAKIA',
    'ORX': 'SLOVAKIA',
    'XSK': 'SLOVAKIA',
    'MOT': 'SLOVENIA',
    'SIM': 'SLOVENIA',
    'SIO': 'SLOVENIA',
    'XFA': 'SOUTH AFRICA',
    'XFC': 'SOUTH AFRICA',
    'XFM': 'SOUTH AFRICA',
    'XFE': 'SOUTH AFRICA',
    'TFG': 'SOUTH AMERICA MOVISTAR',
    'XFV': 'SOUTH ARFICA',
    'SWA': 'SOUTHWEST ASIA',
    'AMN': 'SPAIN',
    'AMO': 'SPAIN',
    'EUS': 'SPAIN',
    'FOP': 'SPAIN',
    'PHE': 'SPAIN',
    'TEE': 'SPAIN',
    'XEC': 'SPAIN',
    'ATL': 'SPAIN',
    'YOG': 'SPAIN',
    'SLK': 'SRI LANKA',
    'BAU': 'SWEDEN',
    'BCN': 'SWEDEN',
    'BME': 'SWEDEN',
    'BSG': 'SWEDEN',
    'BTH': 'SWEDEN',
    'COV': 'SWEDEN',
    'HTS': 'SWEDEN',
    'SEN': 'SWEDEN',
    'TET': 'SWEDEN',
    'TLA': 'SWEDEN',
    'XEE': 'SWEDEN',
    'VDS': 'SWEDEN',
    'TNO': 'SWEDEN',
    'AUO': 'SWITZERLAND',
    'AUT': 'SWITZERLAND',
    'ORG': 'SWITZERLAND',
    'MIG': 'SWITZERLAND',
    'MOZ': 'SWITZERLAND',
    'ORR': 'SWITZERLAND',
    'SUN': 'SWITZERLAND',
    'SUW': 'SWITZERLAND',
    'SWC': 'SWITZERLAND',
    'TWM': 'TAIWAN',
    'SWR': 'SWITZERLAND',
    'BRI': 'TAIWAN',
    'FET': 'TAIWAN',
    'TCC': 'TAIWAN',
    'TCI': 'TAIWAN',
    'CWT': 'TAIWAN',
    'CAM': 'THAILAND',
    'CAT': 'THAILAND',
    'MYM': 'THAILAND',
    'THE': 'THAILAND',
    'THL': 'THAILAND',
    'THO': 'THAILAND',
    'THS': 'THAILAND',
    'THW': 'THAILAND',
    'TTT': 'TRINIDAD & TOBAGO',
    'ABS': 'TUNISIA',
    'OTU': 'TUNISIA',
    'RNG': 'TUNISIA',
    'TUN': 'TUNISIA',
    'BAS': 'TURKEY',
    'KVK': 'TURKEY',
    'TUR': 'TURKEY',
    'TLP': 'TURKEY',
    'TRC': 'TURKEY',
    'TRO': 'TURKEY',
    'SOL': 'TANZANIA',
    'MTN': 'UGANDA',
    'BTU': 'UK & IRE',
    'ALO': 'UKRAINE',
    'FTD': 'UKRAINE',
    'KVR': 'UKRAINE',
    'MSG': 'UKRAINE',
    'OMD': 'UKRAINE',
    'RTL': 'UKRAINE',
    'SEK': 'UKRAINE',
    'UMC': 'UKRAINE',
    'MID': 'UNITED ARAB EMIRATES',
    'VHC': 'UKRAINE',
    'KSS': 'UNITED ARAB EMIRATES',
    'ARB': 'UNITED ARAB EMIRATES',
    'XSG': 'UNITED ARAB EMIRATES',
    'XSB': 'UNITED ARAB EMIRATES',
    'XSD': 'UNITED ARAB EMIRATES',
    'XSI': 'UNITED ARAB EMIRATES',
    'XSN': 'UNITED ARAB EMIRATES',
    'XSS': 'UNITED ARAB EMIRATES',
    'XST': 'UNITED ARAB EMIRATES',
    'XSW': 'UNITED ARAB EMIRATES',
    'AFR': 'UNITED ARAB EMIRATES',
    'ITO': 'UNITED ARAB EMIRATES',
    'LYS': 'UNITED ARAB EMIRATES',
    'XSM': 'UNITED ARAB EMIRATES',
    'BTC': 'UNITED KINGDOM',
    'O2I': 'UNITED KINGDOM',
    'O2U': 'UNITED KINGDOM',
    'ORA': 'UNITED KINGDOM',
    'TMU': 'UNITED KINGDOM',
    'TSC': 'UNITED KINGDOM',
    'VOD': 'UNITED KINGDOM',
    'VOP': 'UNITED KINGDOM',
    'XEU': 'UNITED KINGDOM',
    'VIR': 'UNITED KINGDOM',
    'H3G': 'UNITED KINGDOM',
    'CPW': 'UNITED KINGDOM',
    'EVR': 'UNITED KINGDOM',
    'ACG': 'UNITED STATES OF AMERICA',
    'AIO': 'UNITED STATES OF AMERICA',
    'ATT': 'UNITED STATES OF AMERICA',
    'CRI': 'UNITED STATES OF AMERICA',
    'LRA': 'UNITED STATES OF AMERICA',
    'SPR': 'UNITED STATES OF AMERICA',
    'TFN': 'UNITED STATES OF AMERICA',
    'USC': 'UNITED STATES OF AMERICA',
    'VMU': 'UNITED STATES OF AMERICA',
    'VZW': 'UNITED STATES OF AMERICA',
    'XAR': 'UNITED STATES OF AMERICA',
    'XAS': 'UNITED STATES OF AMERICA',
    'KSG': 'UNKNOWN',
    'QAT': 'UNKNOWN',
    'UFU': 'URUGUAY',
    'AWS': 'USA',
    'BNN': 'USA',
    'DOB': 'USA',
    'TMB': 'USA',
    'CLW': 'USA',
    'UBL': 'UZBEKISTAN',
    'UCL': 'UZBEKISTAN',
    'UZB': 'UZBEKISTAN',
    'CAC': 'UZBEKISTAN CENTRAL ASIA',
    'DGT': 'VENEZUELA',
    'MVL': 'VENEZUELA',
    'VMT': 'VENEZUELA',
    'VNO': 'VENEZUELA',
    'XXV': 'VIETNAM',
    'PHU': 'VIETNAM',
    'XEV': 'VIETNAM',
    'DNA': 'VIETNAM',
    'FPT': 'VIETNAM',
    'SPT': 'VIETNAM',
    'TLC': 'VIETNAM',
    'VTC': 'VIETNAM',
    'VTL': 'VIETNAM',
    'AIR': 'ZAMBIA',
    'MTZ': 'ZAMBIA',
}
