# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Yannick Locque (yanuino)

class FUSError(Exception): ...
class AuthError(FUSError): ...
class InformError(FUSError): ...
class DownloadError(FUSError): ...
class DecryptError(FUSError): ...
class DeviceIdError(FUSError): ...

